### PR TITLE
Issue 39 rename in place

### PR DESCRIPTION
**Pull request by jica**

### CODE REVIEW

**Comment by aljelly** [comment]
I'll test it, but can you resolve conflicts with master please? (custom colours were added since)

**Comment by aljelly** [comment]
For some reason, it looks like `on_stop_editing ()` is triggered several times in certain cases.

For example, try creating two panels and then renaming one to the same name as the other. Two errors show up (it tried to rename it twice). I'm not exactly sure why this happens yet.

**Comment by aljelly** [comment]
The previous height of the title bar:

screenshot from 2017-11-14 13 43 40

What it looks like in this branch:

screenshot from 2017-11-15 16 05 15

---

The previous margin/space between the trash icon and the title bar label:

screenshot from 2017-11-15 16 01 35

What it looks like in this branch:

screenshot from 2017-11-15 16 05 38

**Comment by spheras** [comment]
**I did some changes to update what @aljelly  mention:**
- The on_stop_editing () event is now launched 1 time.
- The cursor doesn't change, and you need to double click on the label to rename (this solves a lot of technical problems, and from my perspective is more useful)

**Problems to solve yet:**
- Right clicking on the editable title bar label when it's not being edited shows the default title bar context menu rather than our own context menu.
- Long window names in the title bar go onto multiple lines rather than showing the ellipsis (the 3 dots cutting off too long text).
- Make the editable title bar label always bold (as it was previously).
- Make the title bar's height the same as it was previously.
- Keep a margin between the trash icon (+ the future properties icon) and the label

@aljelly, regarding this:
> Can we look into adding that little button (that saves/submits your edit) back in?

What do you mean exactly?

**Comment by aljelly** [comment]
> @aljelly, regarding this:
> > - Can we look into adding that little button (that saves/submits your edit) back in?
>
> What do you mean exactly?

I meant the round button here:



In fact, it was removed from Notejot (the app we're basing the EditableLabel on). I think we should just leave it as it is instead (so don't add it). I'll edit my review summary.

> > - Make the editable title bar label always bold (as it was previously).
>
> Isn't it bold?

It depends on the "Text bold" option. If "Text bold" is disabled then the editable label loses the bold weight as well (the bold setting is meant for file/folder labels only).

(Will add a screenshot later)

> - The cursor doesn't change, and you need to double click on the label to rename (this solves a lot of technical problems, and from my perspective is more useful)

I haven't tried the changes yet, but if I'm understanding this correctly: wouldn't removing the cursor change and requiring a double click to edit make it more difficult to discover the fact you can edit the label by (double) clicking on it?

---

Also, there were [some changes to the file](https://github.com/lainsce/notejot/pull/41) we're basing the EditableLabel on, maybe we could manually add these improvements to our file as well?

**Pull request merged**
