### PR TITLE
Code formatting clean up + minor edits

### PR DESCRIPTION
**Pull request by aljelly**
- Ran clean up script on code (based on [elementary's code style guidelines](https://elementary.io/docs/code/reference#code-style)).
- Made some manual formatting edits
- Slightly edited one or two comments
- Corrected `clean_shortchut ()` to `clean_shortcut ()`
- (Panels and Notes) Renamed `delete ()` to `trash ()` which is what it actually does (`delete ()` is to be added)
  - (Photos) Made PhotoManager `delete ()` actually delete the .dfp file (it's easy to add the photo back onto the desktop).
- Lessened repetition of `on_key` event in FolderWindow
- Added `trash ()` to ItemView which simply forwards to the ItemManager's `trash ()`

The large majority of the line changes are from the code formatting script.

This will probably not merge nicely with any other changes or branches because of the large amount of line changes.

### CODE REVIEW

**Comment by spheras** [comment]
@aljelly, what script did you use? is an script or any editor plugin format? (i would like to use too)

**Comment by spheras** [comment]
Please, delete de branch if it has been merged ok. 
Regarding the code style, I would like to use the same script as you. Where can i find it?

The only thing I don't like are the spaces before the equals, i.e.: `this.x         = 110;`
Is this also in the elementary code guide style?

**Comment by aljelly** [comment]
I used [uncrustify](https://github.com/uncrustify/uncrustify) because I found a elementary OS Vala configuration for it. The original was a bit outdated and seemed to have no specified license, however I believe it might be based on [the defaults config included with uncrustify](https://github.com/uncrustify/uncrustify/blob/master/etc/defaults.cfg), and uncrustify is under GPL-2.0. Unfortunately it's not GPL-2.0+ though (and our license is GPL-3.0).

I made some edits to the script. I [added the cleanup config to the branch](https://github.com/spheras/desktopfolder/blob/master/src/uncrustify-elementary-vala.cfg) (which is now merged), but I also [put it in a gist](https://gist.github.com/aljelly/be5c915e54dec795a429f8524af847e8) in case it has to be removed. Build and install uncrustify, then go to `src/` and run uncrustify like this:

```bash
uncrustify -c uncrustify-elementary-vala.cfg */*.vala *.vala --replace
```

There are one or two little quirks with the program though, one of them is it adds a space to the underscore before translatable strings, as in `_("string")` to `_ ("string")`. I expect that's because it regards the underscore as the name of a function. The code still works with the space though, and if you don't mind it looking like that then we can just let it do that. I included `LanguageText.vala` once and then replaced `_ (` with `_(`.

This is what you'd run to not include LanguageText.vala:

```
uncrustify -c uncrustify-elementary-vala.cfg */*.vala Application.vala Resources.vala --replace
```

The other quirk is that having a comment that has a backslash at the end of a comment converts the next line into a comment (like how you can continue lines with a backslash with bash). So it converts this:

```vala
// this is a comment \
this.function ().has_another_one ("inside it")
```
to this:
```vala
// this is a comment \
// this.function ().has_another_one ("inside it")
```

The reason I mention this is that it was doing this for the border drawing code for the notes; the comments were showing the direction of the lines being drawn. `// \` was causing problems.

**Comment by aljelly** [comment]
Also yes, the spacing before and after the equals does seem to be part of elementary's code guidelines. We don't have to follow the style, although I prefer the equals spacing myself. That specific option would be configured with `sp_assign`.

**Comment by spheras** [comment]
sorry, I didn't explain well, I mean the space(s), a lot of spaces :smile:  like this:

`public const int PADDING_X  __________ = 13;`

(I've replaced with _____ because github doesnt respect it, and only put one)

Anyway, if it is automatic, I don't mind to use it as well. Thanks for the explanation.

**Comment by aljelly** [comment]
Oh that's the alignment option, I enabled it because I thought it made it look neater in some cases, like this:

```vala
public const int this.align_to_grid = 24;
public const int this.alignment_x   = 16;
public const int this.alignment_y   = 16;
public const int this.width         = 60;
public const int this.height        = 100;
```

Compared to this:

```vala
public const int this.align_to_grid = 24;
public const int this.alignment_x = 16;
public const int this.alignment_y = 16;
public const int this.width = 60;
```

There's a threshold setting ( `align_assign_thresh` ) in the config that sets a limit for how far the gap can be to stop this sort of thing:

```vala
private List<DesktopFolder.FolderManager> this.is_my_considerably_long_variable_name = 13;
private const int x                                                                  = 2;
```

It's currently set to 20 (spaces). Perhaps the threshold could be set to a lower number or it could be disabled entirely if it's not wanted.

**Comment by spheras** [comment]
@jica, pay attention to this thread. I've created a note of this in the file etc/knowhow to start using uncrustify each time we are pushing code.  Becareful because a lot of md5 and temporal files are created too. You must remove them (I haven't investigate if them can be avoided)

**Comment by aljelly** [comment]
The  `--no-backup` option should work for both files (probably should have added that earlier).

It looks like .gitignore covers them because of the `*~` option.

**Pull request merged**
