### PR TITLE
Latest translations

### PR DESCRIPTION
**Pull request by fossfreedom**
Please can I ask that you make a new release soonest?  I would like to get the latest work into Debian and Ubuntu 20.04LTS.  TIA.

### CODE REVIEW

**Comment by spheras** [comment]
Sure, sorry @fossfreedom, I've been very disconnected from the open source world :(. 
I'm having some days off now, so, I promise to perform the release during these days.  I will get you informed.

**Comment by spheras** [comment]
@fossfreedom, I just released a version ([1.1.2](https://github.com/spheras/desktopfolder/releases/tag/v1.1.2)).  My tests are fine. Please, give it a look and tell me if you see it OK (how can I see whether all the new translations are there?).

Hope its OK.

**Comment by fossfreedom** [comment]
@spheras I note that the tarball name has changed from previous releases.

However the signed .asc file no longer matches the new tarball name.  Please can you make the name the same name-format as the tarball please?

**Comment by spheras** [comment]
mmm OK, done. Check it plz, because I'm not sure why it was .xz in version 1.1.0, probably it doesn't mind, isn't it?

**Comment by fossfreedom** [comment]
many thanks.

the built deb file is the same as yours.  The contents look ok with all the
revised translations.

I've now uploaded this to debian and it will sync to ubuntu later today.

cheers

**Comment by gsbhasin123** [comment]
@fossfreedom Will DesktopFolder be used in 20.04 UB?

**Comment by fossfreedom** [comment]
@gsbhasin123  - no - there are a number of outstanding issues (on the issue tracker) that needs to be addressed first. We'll revisit this for 20.10 depending on progress made.  As always - all contributions to this project is most welcome to help expedite matters.

**Pull request merged**
