### PR TITLE
Update translation files

### PR DESCRIPTION
**Pull request by lvitals**

### CODE REVIEW

**Comment by fossfreedom** [comment]
Hi - translations are managed via transifex now.

It kind of gets very messy if merging in manual pull requests like this - I have to manually push the translation file back up to transifex - and this may overwrite someone's changes that they may have done.

Please can you use transifex? 

https://www.transifex.com/ubuntu-budgie/desktopfolder

**Comment by lvitals** [comment]
Hi, I can use transifex, but how do I correct an existing translation? The translation into Portuguese of Brazil needs to be improved.

**Comment by fossfreedom** [comment]
When you  join the pt_BR team you can click the translate button and then navigate through the existing translations . If you find one that needs updating just change the translation and click save or tab to the next translation.

**Comment by fossfreedom** [comment]
Thanks - I've pulled the latest translations including your pt_BR updates from transifex and its now awaiting review and merging #231

**Comment by spheras** [comment]
merged #231, thanks @lvitals

**Pull request closed without merging**
