### PR TITLE
Added right-click option open-terminal-here

### PR DESCRIPTION
**Pull request by Jacob-Vlijm**
The option is available on both the desktop and panels. 
I also did a bit of uncrustifying, please check if it is the desired result. I used the uncrustify .cfg file, which throws an error: `uncrustify-elementary-vala.cfg:799 Unknown symbol 'align_number_left'`

afbeelding

### CODE REVIEW

**Comment by aljelly** [comment]
Thank you for your PR!

It looks like Uncrustify actually messed with a huge amount of the indentation of loads of files... sorry to ask, but would you be able to redo the changes you made in a different (clean) branch and then push it into this one (or create a new PR if that's annoying) but without uncrustifying if that's not too difficult?

You can see the changes you made unaffected by Uncrustify's messing up here, hopefully this will make it easy to do: https://github.com/spheras/desktopfolder/pull/150/files?utf8=%E2%9C%93&diff=split&w=1

(Maybe uncrustify shouldn't be recommended anymore...)

Also, could you instead make it so that the "Open terminal here" instead appears like this?

right-click-menu-files

So an "Open In > Terminal" at the top, above the New menu. The code for the New menu should hopefully make it easy to do.

**Comment by fossfreedom** [comment]
Hiding "Open Terminal here" in a submenu is not a good solution for something that is used often. Disagree with this approach.  It really does belong as a distinct menu option like "Change Wallpaper" - a distinct action.

I had a very quick look at using uncrustify v0.65 as per the wiki and uncrustify v0.66 (the 18.04 and 18.10 versions) - seems to be touching the same number of files in a very similar way at first glance. Looks to be indenting in a similar way - could be wrong here.

    find . -name "*.vala" -exec uncrustify --replace --no-backup -c ./etc/uncrustify-elementary-vala.cfg {} \;

**Comment by aljelly** [comment]
I don't think the terminal would be used often by non-technical users, which is probably most people. But the intention wasn't so much to hide it away, it was partially to be consistent with elementary.

Perhaps on it's own it would look strange and seem like it's there literally just to keep it out of sight. The idea is that other options would be organised into the "Open in" menu as with the screenshot I posted (like the New submenu that's already in Desktop Folder). For example:

- Open in
  - Files
  - Terminal
  - Other Application...

If all these options were added to the menu without a submenu it would look a bit messy and the menu could start to get long (especially if the app starts remembering what you selected for "Other Application..."). And with multiple options starting with "Open in" it would make sense to group them into a submenu starting with "Open in". It's partially a preparation for that.

**Comment by fossfreedom** [comment]
Ah. Understood now where you are coming from.

We are going to have to find a way to accommodate the elementary approach compared to a linear approach that Nautilus users on other DEs are expecting. In this case the Elementary method  will confuse such users because the  Nautilus position is as currently implemented.

We will have other clashes of style in future between the two user expectations.  Just need to figure the best way technically to accommodate this.

On Wed, 14 Nov 2018, 01:09 aljelly <notifications@github.com<mailto:notifications@github.com> wrote:

I don't think the terminal would be used often by non-technical users, which is probably most people. But the intention wasn't so much to hide it away, it was partially to be consistent with elementary.

Perhaps on it's own it would look strange and seem like it's there literally just to keep it out of sight. The idea is that other options would be organised into the "Open in" menu as with the screenshot I posted (like the New submenu that's already in Desktop Folder). For example:

  *   Open in
     *   Files
     *   Terminal
     *   Other Application...

If all these options were added to the menu without a submenu it would look a bit messy and the menu could start to get long (especially if the app starts remembering what you selected for "Other Application..."). And with multiple options starting with "Open in" it would make sense to group them into a submenu starting with "Open in". It's partially a preparation for that.

**Comment by Jacob-Vlijm** [comment]
@spheras Perfect! Thanks, I will push the un- uncrustified version.

**Comment by Jacob-Vlijm** [comment]
Will do a new PR without uncrustify.

**Pull request closed without merging**
