### PR TITLE
Created readme for arch build instructions

### PR DESCRIPTION
**Pull request by GabMus**

### CODE REVIEW

**Comment by spheras** [comment]
Thank you @GabMus!  I've no expierence with Arch.  Have you tried desktopfolder over Arch.. using gnome??  Is it working properly?

**Comment by GabMus** [comment]
Decently enough, although i was under Wayland and weird behavior was
expected

**Comment by spheras** [comment]
Ok. Thankyou again. I feel we need to start focusing on wayland after the next release.

**Comment by GabMus** [comment]
I think so, there's no point in developing stuff for Xorg anymore. Anyway, nice project, will keep an eye on it 😁

**Pull request merged**
